# Dataset Configuration
dataset:
  name: "nuscenes"
  version: "v1.0-mini"
  data_root: "./nuscenes"
  split: "train"
  
# Image Processing
image:
  height: 900
  width: 1600
  input_size: [384, 1280]  # Resized for model input
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# YOLO Configuration
yolo:
  model_name: "yolov8n"  # Options: yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  confidence_threshold: 0.25
  iou_threshold: 0.45
  classes: ["car", "truck", "bus", "trailer", "construction_vehicle", 
            "pedestrian", "motorcycle", "bicycle", "traffic_cone", "barrier"]

# 3D Estimation Configuration
estimation_3d:
  backbone: "resnet50"  # Options: resnet50, resnet101, vgg16, vgg19, efficientnet_b0
  feature_dim: 2048
  hidden_dim: 512
  output_params:
    dimensions: 3  # width, height, length
    orientation: 1  # yaw angle
    location: 3    # x, y, z in camera coordinates

# BEV Configuration
bev:
  x_range: [-50, 50]  # meters
  y_range: [0, 100]   # meters
  resolution: 0.2     # meters per pixel
  z_range: [-10, 10]  # meters (for filtering)

# Training Configuration
training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "cosine"
  warmup_epochs: 5
  
  # Loss weights
  loss_weights:
    cls: 1.0
    box_2d: 1.0
    box_3d: 2.0
    orientation: 1.5
    depth: 2.0

# Evaluation Configuration
evaluation:
  iou_threshold: 0.5
  distance_threshold: 2.0  # meters for 3D localization
  angle_threshold: 10.0    # degrees for orientation

# Paths
paths:
  checkpoint_dir: "./checkpoints"
  output_dir: "./outputs"
  log_dir: "./logs"
  
# Device Configuration
device: "cuda"  # cuda or cpu
num_workers: 4
seed: 42
